name: Java Documentation Generation

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  generate-docs:
    if: github.event.pull_request.merged == true
    name: Generate Java Documentation and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Generate JavaDocs
        run: mvn -B javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{secrets.DOC_TOKEN}}
          publish_dir: ./target/report/apidocs